### PR TITLE
Fix/paging with filters

### LINKED ISSUE #44: SearcherSingleIndexDataSource doesn't update with filters
Steps to reproduce:
- Take the `PagingSingleIndexDemo`
- Add a button that when pressed adds a filter:
  ```kotlin
  filter.setOnClickListener {
      filterState.notify {
         add(FilterGroupID("Foo"), Filter.Numeric("year".toAttribute(), NumericOperator.GreaterOrEquals, 1993))
          println("Added > 1993")
      }
  }
  ```
- Run the app, click the button: the `Stats` display less hits, but the `MovieAdapterPaged` still displays unfiltered data.

### PR DESCRIPTION
**Pull request by PLNech**
Fixes #44 by adding a `connectFilterState()` that invalidates the DataSource when the state changes.

Paging Demo with working filter button

### CODE REVIEW

File: helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherDataSourceFactory.kt [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+/**
+ * A DataSourceFactory that keeps track of the latest DataSource created,
+ * to invalidate it when a [connected filter state][connectFilterState] changes.
+ */
+abstract class SearcherDataSourceFactory<T> : DataSource.Factory<Int, T>() {
+
+    /**
+     * The last DataSource created by this Factory.
+     */
+    public lateinit var lastDataSource: DataSource<Int, T>
```
Comment (q-litzler) [inline helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherDataSourceFactory.kt]: You don't need this, you can simply do :


```
val pagedList: LiveData<PagedList<T>>

pagedList.value?.dataSource?.invalidate()
```

Comment (q-litzler) [reply helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherDataSourceFactory.kt]: Meaning that the SearcherDataSourceFactory is probably not useful
